name: Build ZMK Firmware

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - board: seeeduino_xiao_ble
            shield: roBa_L
          - board: seeeduino_xiao_ble
            shield: roBa_R
          - board: seeeduino_xiao_ble
            shield: settings_reset

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: zmkfirmware/zmk-build-action@v1
        with:
          board: ${{ matrix.board }}
          shield: ${{ matrix.shield }}
